import { stripLeadingEmoji } from "@/lib/text";

/**
 * Category names in the catalogue carry a decorative emoji prefix
 * ("⏱️ Suivi du Temps"). The UI strips it before display; structured data must
 * too, otherwise the emoji ends up in Google's breadcrumb trail.
 *
 * Delegates to `stripLeadingEmoji` so there is a single implementation — that
 * one handles multi-code-point emoji sequences (variation selectors, ZWJ).
 *
 * Note: `CartPage.tsx` and `ExplorerPage.tsx` each still carry their own copy of
 * this helper — they predate this module and should be pointed here.
 */
export function cleanCategoryLabel(label?: string) {
  return stripLeadingEmoji(label, "");
}

/**
 * Display label for a category in the given language.
 *
 * Falls back to the French name when `nameEn` is missing — 16 of the 23
 * categories have no English name in the catalogue, so English pages currently
 * show French labels. That gap has to be closed in Supabase (the source of
 * truth); `categories_index.json` is generated by sync-supabase-to-json.mjs and
 * must not be hand-edited.
 */
export function getCategoryLabel(
  category: { name?: string; nameEn?: string; id?: string } | undefined,
  lang: string,
) {
  if (!category) return "";
  const raw =
    lang === "en"
      ? category.nameEn || category.name || category.id
      : category.name || category.id;
  return cleanCategoryLabel(raw) || category.id || "";
}
