project_id = "rtfyfuwfdpnsogovkwai"

[functions.seed-content]
verify_jwt = false

[functions.seed-tools-v4]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.translate-tools]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.seed-diagnostic]
verify_jwt = false

[functions.seed-tools-enrichment]
verify_jwt = false

[functions.enrich-tools]
verify_jwt = false
