-- Chunk 2/5 — tools 517 to 1268
BEGIN;

UPDATE tools SET long_description = 'NordPass, c''est gestionnaire de mots de passe par NordVPN. À partir de 1.99€/mois.', long_description_en = 'NordPass is password manager by NordVPN. Starting at €1.99/month.' WHERE slug = 'nordpass';
UPDATE tools SET long_description = 'OneDrive, c''est stockage cloud Microsoft. L''outil est entièrement gratuit.', long_description_en = 'OneDrive is microsoft cloud storage. It''s completely free.' WHERE slug = 'onedrive';
UPDATE tools SET long_description = 'WeTransfer, c''est transfert de fichiers volumineux. L''outil est entièrement gratuit.', long_description_en = 'WeTransfer is large file transfer. It''s completely free.' WHERE slug = 'wetransfer';
UPDATE tools SET long_description = 'Publer, c''est planification et analytics réseaux sociaux. L''outil est entièrement gratuit.', long_description_en = 'Publer is social media scheduling and analytics. It''s completely free.' WHERE slug = 'publer';
UPDATE tools SET long_description = 'BambooHR, c''est logiciel RH et gestion des talents. L''outil est entièrement gratuit.', long_description_en = 'BambooHR is hR software and talent management. It''s completely free.' WHERE slug = 'bamboohr';
UPDATE tools SET long_description = 'Gusto, c''est paie et avantages sociaux. À partir de 40€/mois.', long_description_en = 'Gusto is payroll and employee benefits. Starting at €40/month.' WHERE slug = 'gusto';
UPDATE tools SET long_description = '8fig, c''est plateforme de financement de croissance pour les fondateurs e-commerce. À partir de 5€/mois. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Teachable, c''est plateforme pour créer et vendre des cours en ligne. À partir de 20€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Adobe Firefly, c''est la génération d''images IA intégrée dans Adobe CC. L''outil est entièrement gratuit. Particulièrement pertinent pour les graphiste-da et les photographe.
UPDATE tools SET long_description = 'vcita, c''est plateforme de gestion clients pour PME (rendez-vous. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les coach-formateur.
UPDATE tools SET long_description = 'Aircall Inc., c''est solution de centre d’appels cloud pour les entreprises modernes. À partir de 20€/mois. Particulièrement pertinent pour les manager-dsi et les ecommercant.
UPDATE tools SET long_description = 'Tidio, c''est solution de chat en direct et chatbot pour entreprises. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Clockify, c''est logiciel de suivi du temps (gratuit) pour équipes et projets. À partir de 20€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Adobe Photoshop, c''est le standard mondial de la retouche photo et du compositing. À partir de 26.21€/mois. Particulièrement pertinent pour les graphiste-da et les photographe.
UPDATE tools SET long_description = 'Albato, c''est plateforme no-code pour étendre les intégrations et automatisations SaaS. À partir de 15€/mois. Particulièrement pertinent pour les fondateurs SaaS et les ecommercant.
UPDATE tools SET long_description = 'Trustpilot, c''est plateforme d’avis en ligne pour entreprises et consommateurs. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'DeepSeek, c''est l''IA chinoise open-source qui défie ChatGPT. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les developpeur-solo et les ai-builder.
UPDATE tools SET long_description = 'Adobe Premiere Pro, c''est le logiciel de montage vidéo professionnel de référence. À partir de 26.21€/mois. Particulièrement pertinent pour les motion-video et les créateurs de contenu.
UPDATE tools SET long_description = 'Aloware, c''est solution de centre de contact pour appels et SMS. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Typeform, c''est outil en ligne de création de formulaires et enquêtes interactifs. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Adobe Lightroom, c''est le standard de la gestion et retouche photo RAW. L''outil est entièrement gratuit. Particulièrement pertinent pour les photographe et les graphiste-da.
UPDATE tools SET long_description = 'Cursor, c''est l''IDE IA qui code avec vous en temps réel. À partir de 20€/mois. Particulièrement pertinent pour les developpeur-solo et les ai-builder.
UPDATE tools SET long_description = 'AroundDeal, c''est plateforme d’intelligence B2B pour contacts et informations d’entreprises. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Upwork, c''est place de marché freelance reliant entreprises et freelances. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'DaVinci Resolve, c''est montage, étalonnage, effets visuels et audio en un seul logiciel. Gratuit. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video et les photographe.
UPDATE tools SET long_description = 'Beehiiv, c''est la plateforme newsletter conçue pour la croissance et la monétisation. À partir de 37.31€/mois. Particulièrement pertinent pour les newslettiste-auteur et les créateurs de contenu.
UPDATE tools SET long_description = 'Autonix, c''est outil de suivi de QR codes et d’analytique pour agences et marketers. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'WooCommerce, c''est plateforme e-commerce pour WordPress. À partir de 15€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'GitHub Copilot, c''est l''assistant de code IA intégré dans votre éditeur. À partir de 8.66€/mois. Particulièrement pertinent pour les developpeur-solo et les cto-lead-tech.
UPDATE tools SET long_description = 'Krea AI, c''est génération d''images IA en temps réel avec contrôle créatif avancé. À partir de 8.66€/mois. Particulièrement pertinent pour les graphiste-da et les motion-video.
UPDATE tools SET long_description = 'Auvik, c''est plateforme de gestion IT pour les réseaux et infrastructures. À partir de 10€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Wrike, c''est logiciel de gestion de projet pour équipes. À partir de 15€/mois. Particulièrement pertinent pour les manager-dsi et les fondateurs SaaS.
UPDATE tools SET long_description = 'Zapier, c''est outil d’automatisation pour connecter des applications et workflows. À partir de 17.31€/mois. Particulièrement pertinent pour les consultants B2B et les ecommercant.
UPDATE tools SET long_description = 'Datadog, c''est observabilité complète : logs, métriques, APM, alertes en temps réel. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les cto-lead-tech et les developpeur-solo.
UPDATE tools SET long_description = 'Getida, c''est solution d’audit et remboursement Amazon FBA. À partir de 10€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Plutio, c''est plateforme de gestion tout-en-un pour freelances (projets. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Readymag, c''est design éditorial web avec animations avancées. À partir de 16€/mois.
UPDATE tools SET long_description = 'Boast, c''est plateforme d’automatisation des déclarations de crédit R&D. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Zoho, c''est suite d’outils de productivité en ligne et applications SaaS. À partir de 15€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Táve, c''est studio manager pour photographes et vidéastes. À partir de 22€/mois.
UPDATE tools SET long_description = 'BoomPop, c''est service d’organisation d’événements d’entreprise et networking. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Snov.io, c''est plateforme d’automatisation des ventes (recherche d’emails. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les fondateurs SaaS et les consultants B2B.
UPDATE tools SET long_description = 'Discord, c''est messagerie vocale et textuelle pour communautés. L''outil est entièrement gratuit.', long_description_en = 'Discord is voice and text messaging for communities. It''s completely free.' WHERE slug = 'discord';
UPDATE tools SET long_description = 'VidIQ, c''est analytics YouTube et IA pour trouver les sujets viraux et optimiser chaque vidéo. À partir de 6.06€/mois. Particulièrement pertinent pour les créateurs de contenu.
UPDATE tools SET long_description = 'Pika Labs, c''est génération vidéo IA centrée sur l''animation de personnages et d''objets. À partir de 6.93€/mois. Particulièrement pertinent pour les motion-video et les créateurs de contenu.
UPDATE tools SET long_description = 'Brand24, c''est outil de veille médiatique pour suivre les mentions de marque en ligne. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Elfsight, c''est collection de widgets pour sites web (flux sociaux. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Ideogram, c''est génération d''images IA avec texte intégré — le meilleur du marché pour la typo. À partir de 6.93€/mois. Particulièrement pertinent pour les graphiste-da et les community-manager.
UPDATE tools SET long_description = 'Suno, c''est génération musicale IA avec paroles et voix intégrées. À partir de 8.66€/mois. Particulièrement pertinent pour les créateurs de contenu et les motion-video.
UPDATE tools SET long_description = 'Basecamp, c''est logiciel de gestion de projet et de collaboration d’équipe. À partir de 12.99€/mois. Particulièrement pertinent pour les manager-dsi et les fondateurs SaaS.
UPDATE tools SET long_description = 'Buddy Punch, c''est pointage en ligne pour le suivi du temps des employés. À partir de 15€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Hex, c''est notebooks data collaboratifs avec publication en apps interactives. À partir de 20.78€/mois. Particulièrement pertinent pour les data-analyst.
UPDATE tools SET long_description = 'Rippling, c''est rH, paie et gestion IT unifiée. À partir de 8€/mois.', long_description_en = 'Rippling is unified HR, payroll, and IT management. Starting at €8/month.' WHERE slug = 'rippling';
UPDATE tools SET long_description = 'Lovable, c''est génération d''applications full-stack depuis un prompt avec Supabase intégré. À partir de 17.32€/mois. Particulièrement pertinent pour les fondateurs SaaS et les ai-builder.
UPDATE tools SET long_description = 'Otter.ai, c''est transcription et résumé automatique de réunions en temps réel. À partir de 8.66€/mois. Particulièrement pertinent pour les consultants B2B et les manager-dsi.
UPDATE tools SET long_description = 'Sendinblue, c''est logiciel d’automatisation marketing et emailing. À partir de 5€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Figma, c''est l''outil de design d''interfaces pour créer maquettes et prototypes. À partir de 15€/mois. Particulièrement pertinent pour les ux-ui et les graphiste-da.
UPDATE tools SET long_description = 'Reply.io, c''est automatisation cold email et prospection multi-canaux. À partir de 51.96€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'SimpleTexting, c''est plateforme d’envoi de campagnes SMS marketing et alertes. À partir de 10€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Plausible Analytics, c''est l''alternative RGPD-friendly à Google Analytics, simple et respectueuse. À partir de 7.79€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'CallHippo, c''est système de téléphonie cloud pour entreprises. À partir de 15€/mois. Particulièrement pertinent pour les manager-dsi et les ecommercant.
UPDATE tools SET long_description = 'Zoom, c''est visioconférence et réunions en ligne. À partir de 13.33€/mois.', long_description_en = 'Zoom is video conferencing and online meetings. Starting at €13.33/month.' WHERE slug = 'zoom';
UPDATE tools SET long_description = 'CallRail, c''est plateforme d’intelligence d’appels pour suivi et attribution de leads. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les ecommercant et les community-manager.
UPDATE tools SET long_description = 'Campaigner, c''est solution puissante de marketing email et SMS pour entreprises. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Simvoly, c''est constructeur de sites web et plateforme e-commerce. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les coach-formateur.
UPDATE tools SET long_description = 'Castmagic, c''est outil de transformation rapide de tout format audio en contenu. À partir de 20€/mois. Particulièrement pertinent pour les graphiste-da et les community-manager.
UPDATE tools SET long_description = 'Razorpay, c''est passerelle de paiement et services financiers pour entreprises en Inde. À partir de 15€/mois. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Reflect, c''est notes networked avec IA intégrée et backlinks. À partir de 10€/mois.
UPDATE tools SET long_description = 'Clearbit, c''est outil d’enrichissement de données et insights pour marketing et ventes. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'QuickBooks, c''est logiciel de comptabilité pour petites entreprises. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les daf-finance et les consultants B2B.
UPDATE tools SET long_description = 'Legalstart, c''est création et gestion juridique d''entreprise en ligne. À partir de 15€/mois.
UPDATE tools SET long_description = 'Close, c''est cRM avec outils de communication intégrés pour les ventes. À partir de 15€/mois. Particulièrement pertinent pour les fondateurs SaaS et les ecommercant.
UPDATE tools SET long_description = 'Vimeo, c''est plateforme d’hébergement et de partage vidéo professionnelle. À partir de 15€/mois. Particulièrement pertinent pour les graphiste-da et les community-manager.
UPDATE tools SET long_description = 'CloudTask Marketplace, c''est marketplace de talents B2B RevOps en freelance. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les fondateurs SaaS et les ecommercant.
UPDATE tools SET long_description = 'Podcastle, c''est enregistrement, édition et transcription de podcasts. À partir de 12€/mois.
UPDATE tools SET long_description = 'Tabnine, c''est assistant de code IA avec modèle privé — pour les équipes soucieuses de confidentialité. À partir de 10.39€/mois. Particulièrement pertinent pour les developpeur-solo et les cto-lead-tech.
UPDATE tools SET long_description = 'Leadflow, c''est générateur de leads immobilier alimenté par l’IA. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Payhawk, c''est plateforme tout-en-un dépenses, cartes et factures. À partir de 12€/mois.
UPDATE tools SET long_description = 'Notion AI, c''est iA intégrée dans Notion : rédaction, résumé, traduction directement dans vos docs. À partir de 6.93€/mois. Particulièrement pertinent pour les consultants B2B et les product-manager.
UPDATE tools SET long_description = 'Coast, c''est carte carburant intelligente et gestion des dépenses pour entreprises. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Cognism, c''est plateforme d’intelligence commerciale B2B (contacts et données entreprises). À partir de 10€/mois. Particulièrement pertinent pour les fondateurs SaaS et les consultants B2B.
UPDATE tools SET long_description = 'Crowdfire Inc, c''est plateforme de gestion des réseaux sociaux. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Integrately, c''est automatisations en 1 clic entre 1000+ apps. À partir de 20€/mois.
UPDATE tools SET long_description = 'Whisper (OpenAI), c''est transcription audio open source d''OpenAI. Précis, multilingue, gratuit. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les podcasteur et les créateurs de contenu.
UPDATE tools SET long_description = 'Deputy, c''est simplifie la planification et réduit les coûts de main-d’œuvre. À partir de 10€/mois. Particulièrement pertinent pour les manager-dsi et les rh-recruteur.
UPDATE tools SET long_description = 'Doppler, c''est gestion centralisée des secrets et variables d''environnement. La version de base est gratuite, avec des options payantes pour aller plus loin.
UPDATE tools SET long_description = 'Adobe Podcast AI, c''est amélioration audio IA : suppression de bruit, égalisation automatique, studio qualité. L''outil est entièrement gratuit. Particulièrement pertinent pour les podcasteur et les créateurs de contenu.
UPDATE tools SET long_description = 'DesktopReady, c''est solution de bureau virtuel Azure. À partir de 10€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Draftbit, c''est générateur d’applications natives (avec code) pour mobiles. À partir de 20€/mois. Particulièrement pertinent pour les developpeur-solo et les ai-builder.
UPDATE tools SET long_description = 'doola, c''est aide les entrepreneurs web2 & web3 à créer et gérer leur entreprise. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Soldo, c''est cartes prépayées et gestion des frais professionnels. À partir de 6€/mois.
UPDATE tools SET long_description = 'Buzzsprout, c''est l''hébergement podcast le plus simple à prendre en main. Distribution automatique. À partir de 10.39€/mois. Particulièrement pertinent pour les podcasteur.
UPDATE tools SET long_description = 'EasyDMARC, c''est saaS pour résoudre les problèmes de sécurité et délivrabilité email. À partir de 10€/mois. Particulièrement pertinent pour les manager-dsi et les developpeur-solo.
UPDATE tools SET long_description = 'Kelio, c''est gestion des temps et planification RH. À partir de 8€/mois.
UPDATE tools SET long_description = 'Audacity, c''est logiciel de montage audio open source. Gratuit, puissant, universel. L''outil est entièrement gratuit. Particulièrement pertinent pour les podcasteur et les créateurs de contenu.
UPDATE tools SET long_description = 'Finale Inventory, c''est solution de gestion des stocks pour vendeurs à gros volume. À partir de 10€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Captaindoc, c''est automatisation de documents juridiques et contractuels. À partir de 19€/mois.
UPDATE tools SET long_description = 'Podia, c''est vente de cours, webinaires et téléchargements numériques. 0% commission. À partir de 28.58€/mois. Particulièrement pertinent pour les coach-formateur et les créateurs de contenu.
UPDATE tools SET long_description = 'Format, c''est constructeur de portfolio en ligne pour professionnels créatifs. À partir de 20€/mois. Particulièrement pertinent pour les graphiste-da et les community-manager.
UPDATE tools SET long_description = 'Rydoo, c''est notes de frais automatisées avec OCR. À partir de 8€/mois.

COMMIT;
