-- Chunk 3/5 — tools 1273 to 2020
BEGIN;

UPDATE tools SET long_description = 'Buffer, c''est planification de posts sur tous les réseaux. Simple, propre, efficace. À partir de 5.2€/mois. Particulièrement pertinent pour les community-manager et les créateurs de contenu.
UPDATE tools SET long_description = 'Front, c''est hub de communication client pour les équipes. À partir de 15€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Workday, c''est hCM et finance cloud pour grandes entreprises. À partir de 99€/mois.
UPDATE tools SET long_description = 'Jira, c''est la référence de la gestion de projet Agile pour équipes tech. À partir de 6.71€/mois. Particulièrement pertinent pour les cto-lead-tech et les product-manager.
UPDATE tools SET long_description = 'Ownr, c''est plateforme d’enregistrement et de création d’entreprises (Canada). La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'SignRequest, c''est signature électronique simple et rapide. À partir de 7€/mois.
UPDATE tools SET long_description = 'Sprout Social, c''est gestion réseaux sociaux premium avec CRM social et analytics avancés. À partir de 215.64€/mois. Particulièrement pertinent pour les community-manager et les manager-dsi.
UPDATE tools SET long_description = 'Packhelp, c''est marketplace de packagings personnalisés. À partir de 10€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Silae, c''est logiciel de paie et gestion sociale française. À partir de 35€/mois.
UPDATE tools SET long_description = 'Typefully, c''est rédaction et planification de threads Twitter/X et posts LinkedIn sans distraction. À partir de 10.39€/mois. Particulièrement pertinent pour les newslettiste-auteur et les consultants B2B.
UPDATE tools SET long_description = 'Gorgias, c''est service client e-commerce transformant le support en centre de profit. À partir de 15€/mois. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Wolters Kluwer, c''est solutions de conformité et veille juridique. À partir de 49€/mois.
UPDATE tools SET long_description = 'Kajabi, c''est la plateforme tout-en-un pour créateurs : cours, communauté, email, paiements. À partir de 47.63€/mois. Particulièrement pertinent pour les coach-formateur et les créateurs de contenu.
UPDATE tools SET long_description = 'Hive, c''est plateforme de productivité pour équipes performantes. À partir de 15€/mois. Particulièrement pertinent pour les manager-dsi et les fondateurs SaaS.
UPDATE tools SET long_description = 'Bloom, c''est cRM et portail client pour créatifs et photographes. À partir de 13€/mois.
UPDATE tools SET long_description = 'Metabase, c''est outil de BI open source. Créez des dashboards depuis votre base de données sans SQL. À partir de 433.01€/mois. Particulièrement pertinent pour les data-analyst et les product-manager.
UPDATE tools SET long_description = 'Hostfully, c''est plateforme de gestion de locations de vacances. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Legifrance Pro, c''est accès aux textes juridiques français officiels. La version de base est gratuite, avec des options payantes pour aller plus loin.
UPDATE tools SET long_description = 'Productboard, c''est outil de discovery produit : collecte feedback, priorisation, roadmap. À partir de 17.32€/mois. Particulièrement pertinent pour les product-manager et les fondateurs SaaS.
UPDATE tools SET long_description = 'Houzz Pro, c''est solution tout-en-un pour gérer les projets de construction résidentielle. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Connective, c''est signatures électroniques et identité numérique. À partir de 15€/mois.
UPDATE tools SET long_description = 'BAO Boa, c''est animation de lignes et formes SVG dans After Effects. Tracés organiques. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video.
UPDATE tools SET long_description = 'InboxAlly, c''est plateforme pour améliorer la délivrabilité et taux d’ouverture des emails. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Microsoft Project, c''est gestion de projet avancée Microsoft. À partir de 25€/mois.
UPDATE tools SET long_description = 'PagerDuty, c''est gestion des incidents en temps réel avec astreintes et escalade automatique. À partir de 18.19€/mois. Particulièrement pertinent pour les cto-lead-tech et les manager-dsi.
UPDATE tools SET long_description = 'Instapage, c''est générateur de landing pages et plateforme d’optimisation. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Lemlist, c''est outreach email personnalisé avec séquences automatisées. À partir de 39€/mois.
UPDATE tools SET long_description = 'Animation Composer 3, c''est bibliothèque de presets d''animation et de transitions pour After Effects. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video.
UPDATE tools SET long_description = 'Jobber, c''est logiciel pour gérer et développer les entreprises de services. À partir de 20€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Nusii, c''est logiciel de propositions commerciales pour agences. À partir de 29€/mois.
UPDATE tools SET long_description = 'GifGun, c''est export GIF directement depuis After Effects en un clic. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video et les community-manager.
UPDATE tools SET long_description = 'Kavkom, c''est solution de téléphonie IP pour communications d’entreprise. À partir de 20€/mois. Particulièrement pertinent pour les manager-dsi et les ecommercant.
UPDATE tools SET long_description = 'Kissmetrics, c''est outil d’analytics comportemental pour augmenter conversions & engagement. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'KeepTruckin, c''est logiciel de gestion de flottes pour entreprises de transport. À partir de 10€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'PhantomBuster, c''est extraction de données et automatisation LinkedIn. À partir de 56€/mois.
UPDATE tools SET long_description = 'Figma Tokens (Tokens Studio), c''est gestion des design tokens dans Figma avec sync Git. Indispensable pour les design systems. À partir de 7.79€/mois. Particulièrement pertinent pour les ux-ui et les developpeur-solo.
UPDATE tools SET long_description = 'Landbot, c''est générateur de chatbot pour automatiser la capture de leads et interactions client. À partir de 15€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Waalaxy, c''est prospection LinkedIn automatisée. À partir de 40€/mois.
UPDATE tools SET long_description = 'RubberHose 2, c''est animation de membres et tentacules organiques sans rigging complexe dans AE. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video.
UPDATE tools SET long_description = 'LeadSquared, c''est plateforme d’exécution commerciale et d’automatisation marketing. À partir de 10€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Looka, c''est plateforme de création de logos par IA. À partir de 20€/mois. Particulièrement pertinent pour les graphiste-da et les community-manager.
UPDATE tools SET long_description = 'Lendio, c''est service de prêts professionnels avec multiples options de financement. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Arc Browser, c''est navigateur repensé pour la productivité. La version de base est gratuite, avec des options payantes pour aller plus loin.
UPDATE tools SET long_description = 'Mailgun, c''est service d’envoi d’emails pour développeurs. À partir de 10€/mois. Particulièrement pertinent pour les developpeur-solo et les fondateurs SaaS.
UPDATE tools SET long_description = 'Notionlytics, c''est analytics pour pages Notion partagées. À partir de 5€/mois.
UPDATE tools SET long_description = 'Manifest AI, c''est chatbot IA alimenté par GPT pour de meilleures interactions client. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Loopio, c''est automatisation des réponses RFP et appels d''offres. À partir de 50€/mois.
UPDATE tools SET long_description = 'Moosend, c''est outil d’email marketing et d’automatisation. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Navan, c''est solution tout-en-un de gestion des voyages et notes de frais. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'MyCase, c''est solution de gestion de dossiers juridiques pour cabinets B2C. À partir de 10€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Netchex, c''est solution de gestion RH et paie. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Onramp Funds, c''est fournit des financements aux marchands pour soutenir leur croissance. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'SysAid, c''est logiciel de gestion des services IT (ITSM). À partir de 10€/mois. Particulièrement pertinent pour les manager-dsi et les cto-lead-tech.
UPDATE tools SET long_description = 'Topaz Video AI, c''est upscaling et amélioration vidéo par IA. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les motion-video et les photographe.
UPDATE tools SET long_description = 'OpenPhone, c''est système téléphonique tout-en-un pour équipes. À partir de 15€/mois. Particulièrement pertinent pour les fondateurs SaaS et les consultants B2B.
UPDATE tools SET long_description = 'HeyGen, c''est création de vidéos avec avatars IA et traduction automatique. À partir de 25.11€/mois. Particulièrement pertinent pour les créateurs de contenu et les coach-formateur.
UPDATE tools SET long_description = 'Pagecloud, c''est constructeur de site web et boutique en ligne. À partir de 15€/mois. Particulièrement pertinent pour les graphiste-da et les fondateurs SaaS.
UPDATE tools SET long_description = 'Payoneer, c''est plateforme de paiements transfrontaliers pour entreprises. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les daf-finance.
UPDATE tools SET long_description = 'Ghost, c''est plateforme de publication et newsletter. À partir de 9€/mois.', long_description_en = 'Ghost is publishing platform and newsletter. Starting at €9/month.' WHERE slug = 'ghost';
UPDATE tools SET long_description = 'PayPal, c''est paiements en ligne et transferts. L''outil est entièrement gratuit.', long_description_en = 'PayPal is online payments and transfers. It''s completely free.' WHERE slug = 'paypal';
UPDATE tools SET long_description = 'Gumroad, c''est vente de produits numériques. L''outil est entièrement gratuit.', long_description_en = 'Gumroad is digital product sales. It''s completely free.' WHERE slug = 'gumroad';
UPDATE tools SET long_description = 'Lemon Squeezy, c''est paiements pour créateurs et SaaS. L''outil est entièrement gratuit.', long_description_en = 'Lemon Squeezy is payments for creators and SaaS. It''s completely free.' WHERE slug = 'lemonsqueezy';
UPDATE tools SET long_description = 'Wave, c''est comptabilité et facturation gratuite. L''outil est entièrement gratuit.', long_description_en = 'Wave is free accounting and invoicing. It''s completely free.' WHERE slug = 'wave';
UPDATE tools SET long_description = 'PipelinePRO, c''est plateforme de gestion de pipeline de ventes et d’automatisation marketing. À partir de 20€/mois. Particulièrement pertinent pour les ecommercant et les fondateurs SaaS.
UPDATE tools SET long_description = 'Spendesk, c''est gestion des dépenses d''entreprise : cartes virtuelles, notes de frais, approbations. À partir de 99€/mois. Particulièrement pertinent pour les daf-finance et les manager-dsi.
UPDATE tools SET long_description = 'ProtoPie, c''est prototypage interactif avancé sans code. Interactions complexes impossibles dans Figma. À partir de 11.26€/mois. Particulièrement pertinent pour les ux-ui.
UPDATE tools SET long_description = 'Luminar Neo, c''est retouche IA pour Photoshop/Lightroom : remplacement de ciel, portrait IA, atmosphère. À partir de 12.12€/mois. Particulièrement pertinent pour les photographe et les graphiste-da.
UPDATE tools SET long_description = 'AutoCAD, c''est le standard mondial du dessin technique 2D et 3D. À partir de 190.53€/mois. Particulièrement pertinent pour les architecte-bim et les scenographe.
UPDATE tools SET long_description = 'Topaz Gigapixel AI, c''est upscaling IA d''images jusqu''à 6x avec préservation des détails. Le meilleur du marché. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les photographe et les graphiste-da.
UPDATE tools SET long_description = 'Maze, c''est tests utilisateurs continus directement depuis vos prototypes Figma. À partir de 64.95€/mois. Particulièrement pertinent pour les ux-ui et les product-manager.
UPDATE tools SET long_description = 'Hotjar, c''est heatmaps, replays de sessions et sondages pour comprendre le comportement utilisateur. À partir de 27.71€/mois. Particulièrement pertinent pour les ux-ui et les product-manager.
UPDATE tools SET long_description = 'Runway, c''est génération et édition vidéo par IA. Le standard du genre. À partir de 12.99€/mois. Particulièrement pertinent pour les motion-video et les créateurs de contenu.
UPDATE tools SET long_description = 'Leonardo AI, c''est génération d''images IA avec fine-tuning et modèles spécialisés. À partir de 10.39€/mois. Particulièrement pertinent pour les graphiste-da et les illustrateur.
UPDATE tools SET long_description = 'Motion Bro, c''est gestionnaire de presets et extensions pour After Effects. À partir de 9€/mois. Particulièrement pertinent pour les motion-video.
UPDATE tools SET long_description = 'CapCut, c''est montage vidéo mobile et desktop pour les créateurs de contenu. À partir de 8.66€/mois. Particulièrement pertinent pour les créateurs de contenu.
UPDATE tools SET long_description = 'Riverside, c''est enregistrement podcast et vidéo en qualité studio, à distance. À partir de 12.99€/mois. Particulièrement pertinent pour les podcasteur et les créateurs de contenu.
UPDATE tools SET long_description = 'PostHog, c''est suite analytics produit open source : events, replays, feature flags, A/B. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les fondateurs SaaS et les developpeur-solo.
UPDATE tools SET long_description = 'Personio, c''est sIRH complet pour PME : recrutement, onboarding, paie, congés. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les rh-recruteur et les manager-dsi.
UPDATE tools SET long_description = 'Enscape, c''est rendu temps réel et VR pour Revit, SketchUp, Rhino. Présentations client immersives. À partir de 72.75€/mois. Particulièrement pertinent pour les architecte-bim et les scenographe.
UPDATE tools SET long_description = 'Lumion, c''est rendu architectural 3D rapide avec bibliothèque massive d''assets. À partir de 155.02€/mois. Particulièrement pertinent pour les architecte-bim et les scenographe.
UPDATE tools SET long_description = 'ChatGPT, c''est l''assistant IA généraliste d''OpenAI. À partir de 17.32€/mois. Particulièrement pertinent pour les graphiste-da et les motion-video.
UPDATE tools SET long_description = 'Claude, c''est l''assistant IA d''Anthropic orienté rédaction, analyse et raisonnement. À partir de 14.43€/mois. Particulièrement pertinent pour les consultants B2B et les newslettiste-auteur.
UPDATE tools SET long_description = 'Base44, c''est créez des apps complètes avec l''IA, sans coder. À partir de 17.32€/mois. Particulièrement pertinent pour les developpeur-solo et les ai-builder.
UPDATE tools SET long_description = 'ElevenLabs, c''est l''IA de synthèse vocale ultra-réaliste pour créer du contenu audio. À partir de 4.33€/mois. Particulièrement pertinent pour les podcasteur et les créateurs de contenu.
UPDATE tools SET long_description = 'ClickUp, c''est la plateforme tout-en-un pour gérer projets, tâches et collaboration. À partir de 6.06€/mois. Particulièrement pertinent pour les manager-dsi et les fondateurs SaaS.
UPDATE tools SET long_description = 'Logome.ai, c''est générateur de logos IA en quelques minutes. À partir de 1.45€/mois. Particulièrement pertinent pour les graphiste-da et les fondateurs SaaS.
UPDATE tools SET long_description = 'Notion, c''est le cerveau externe tout-en-un. À partir de 9.5€/mois. Particulièrement pertinent pour les consultants B2B et les developpeur-solo.
UPDATE tools SET long_description = 'Calendly, c''est la fin des emails ''tu es dispo quand ?''. À partir de 8.66€/mois. Particulièrement pertinent pour les consultants B2B et les coach-formateur.
UPDATE tools SET long_description = 'Canva, c''est le design pour les non-designers. À partir de 11.26€/mois. Particulièrement pertinent pour les community-manager et les créateurs de contenu.
UPDATE tools SET long_description = 'Stripe, c''est l''infrastructure de paiement d''internet. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les fondateurs SaaS et les ecommercant.
UPDATE tools SET long_description = 'Indy, c''est compta et facturation automatisées pour indépendants. À partir de 20€/mois. Particulièrement pertinent pour les consultants B2B et les graphiste-da.
UPDATE tools SET long_description = 'Google Drive, c''est le standard du stockage cloud. À partir de 1.73€/mois. Particulièrement pertinent pour les consultants B2B et les graphiste-da.
UPDATE tools SET long_description = 'Tally, c''est le Typeform gratuit (en mieux). La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'Todoist, c''est la to-do list pure et dure. À partir de 7€/mois. Particulièrement pertinent pour les consultants B2B et les graphiste-da.
UPDATE tools SET long_description = 'Obsidian, c''est votre second cerveau, en local. La version de base est gratuite, avec des options payantes pour aller plus loin. Particulièrement pertinent pour les consultants B2B et les newslettiste-auteur.
UPDATE tools SET long_description = 'Raycast, c''est le lanceur d''applications qui remplace 10 outils. À partir de 6.93€/mois. Particulièrement pertinent pour les developpeur-solo et les ai-builder.
UPDATE tools SET long_description = 'Linear, c''est la gestion de projet pour les équipes tech exigeantes. À partir de 8.66€/mois. Particulièrement pertinent pour les developpeur-solo et les cto-lead-tech.
UPDATE tools SET long_description = 'Midjourney, c''est l''IA génératrice d''images pour les pros. À partir de 8.66€/mois. Particulièrement pertinent pour les graphiste-da et les motion-video.
UPDATE tools SET long_description = 'Blueink eSignatures, c''est plateforme de signatures électroniques et suivi de documents. À partir de 15€/mois. Particulièrement pertinent pour les consultants B2B et les fondateurs SaaS.
UPDATE tools SET long_description = 'GetResponse, c''est la plateforme tout-en-un pour email marketing et automatisation. À partir de 12.99€/mois. Particulièrement pertinent pour les coach-formateur et les ecommercant.

COMMIT;
