-- === _bootstrap-public-tools.4.12.sql — REJEU JETABLE UNIQUEMENT ===
-- Reproduit public.tools (colonnes A2) avec le référentiel/FK categories réel,
-- sans les 9 colonnes A1 (ajoutées par la migration), + RLS + policy publique de lecture.
create table public.categories(id varchar(50) primary key, name varchar(255) not null, slug varchar(255) not null, description text);
insert into public.categories(id,name,slug) values
  ('ai-general','ai-general','ai-general'),
  ('analytics','analytics','analytics'),
  ('automation','automation','automation'),
  ('budgeting-fpa','budgeting-fpa','budgeting-fpa'),
  ('communication','communication','communication'),
  ('communication-team','communication-team','communication-team'),
  ('creation','creation','creation'),
  ('design-tools','design-tools','design-tools'),
  ('email-productivity','email-productivity','email-productivity'),
  ('erp','erp','erp'),
  ('finance','finance','finance'),
  ('formation-education','formation-education','formation-education'),
  ('hris-payroll','hris-payroll','hris-payroll'),
  ('legal-contracts','legal-contracts','legal-contracts'),
  ('nocode-web','nocode-web','nocode-web'),
  ('organization','organization','organization'),
  ('productivity-tracking','productivity-tracking','productivity-tracking'),
  ('project-management','project-management','project-management'),
  ('security','security','security'),
  ('storage','storage','storage'),
  ('vendor-risk-data','vendor-risk-data','vendor-risk-data');
create table public.tools (
  id varchar(50) primary key,
  slug varchar(255),
  name varchar(255),
  category varchar(50) references public.categories(id),
  tool_type text,
  website_url varchar(500),
  affiliate_link varchar(500),
  logo varchar(10),
  og_image_url text,
  short_description text,
  short_description_en text,
  long_description text,
  long_description_en text,
  pricing jsonb,
  pricing_en jsonb,
  default_monthly_price numeric,
  pricing_v5 jsonb,
  verdict jsonb,
  verdict_en jsonb,
  pros jsonb,
  pros_en jsonb,
  cons jsonb,
  cons_en jsonb,
  covers jsonb,
  use_cases jsonb,
  use_cases_en jsonb,
  relevant_for jsonb,
  seo jsonb,
  articles jsonb,
  alternatives jsonb,
  functional_needs jsonb,
  verticals jsonb,
  personas jsonb,
  better_alternative jsonb,
  free_alternative text,
  migration_guide jsonb,
  downgrade_plan jsonb,
  solo_relevance varchar(50),
  team_relevance varchar(50),
  time_gained_hours_per_month integer,
  substitutable boolean,
  prescription_quality text,
  prescription_output jsonb,
  prescription_block_reasons jsonb,
  prescription_context_questions jsonb,
  substitution_cluster_v2 text,
  decision_policy_v3 jsonb,
  pertinence_by_persona jsonb,
  force_silence boolean,
  ia_use_case jsonb,
  host_app text,
  bundle_parent text
);
alter table public.tools enable row level security;
create policy "Public read tools" on public.tools for select to anon, authenticated using (true);
grant select on public.tools to anon, authenticated;
