
-- SEED CLUSTERS for all 5 personas

-- ══════════════ THEO (Tech/Dev) — 9 clusters ══════════════
INSERT INTO clusters (id, persona, "order", question, question_en, why, cols, tool_ids) VALUES
('theo-1', 'THEO', 1, 'Tes assistants de code IA', 'Your AI code assistants', 'Les outils qui écrivent du code avec toi', 2, '["github-copilot","cursor","tabnine","bolt-new","lovable","replit"]'),
('theo-2', 'THEO', 2, 'Tes LLMs (ChatGPT, Claude…)', 'Your LLMs (ChatGPT, Claude…)', 'Les IA conversationnelles que tu utilises', 2, '["chatgpt","claude","gemini","perplexity","deepseek"]'),
('theo-3', 'THEO', 3, 'Tes outils d''hébergement et déploiement', 'Your hosting & deployment tools', 'Là où tu déploies tes projets', 2, '["vercel","netlify","railway","render","fly-io","heroku","digitalocean"]'),
('theo-4', 'THEO', 4, 'Tes outils de base de données', 'Your database tools', 'Où tu stockes et requêtes tes données', 2, '["supabase","firebase","planetscale","neon","mongodb-atlas","airtable"]'),
('theo-5', 'THEO', 5, 'Tes outils de monitoring et analytics', 'Your monitoring & analytics tools', 'Comment tu surveilles tes apps', 2, '["sentry","datadog","posthog","amplitude","hotjar","plausible"]'),
('theo-6', 'THEO', 6, 'Tes outils de gestion de projet', 'Your project management tools', 'Comment tu organises ton travail', 2, '["linear","notion","jira","asana","trello","clickup","monday-com"]'),
('theo-7', 'THEO', 7, 'Tes outils de communication', 'Your communication tools', 'Comment tu communiques avec tes clients', 2, '["slack","discord","zoom","cal-com","calendly","loom"]'),
('theo-8', 'THEO', 8, 'Tes outils d''automatisation', 'Your automation tools', 'Les connecteurs et workflows', 2, '["zapier","make","n8n"]'),
('theo-9', 'THEO', 9, 'Tes outils de sécurité et mots de passe', 'Your security & password tools', 'Comment tu protèges tes accès', 2, '["1password","bitwarden","dashlane","lastpass","nordpass"]'),

-- ══════════════ SOFIA (Créatif) — 13 clusters ══════════════
('sofia-1', 'SOFIA', 1, 'Tes outils de design UI/UX', 'Your UI/UX design tools', 'Les outils de conception d''interfaces', 2, '["figma","sketch","adobe-xd","framer","webflow"]'),
('sofia-2', 'SOFIA', 2, 'Tes outils Adobe', 'Your Adobe tools', 'Ta suite Adobe', 2, '["photoshop","illustrator","indesign","lightroom","premiere-pro","after-effects","adobe-creative-cloud"]'),
('sofia-3', 'SOFIA', 3, 'Tes outils de retouche photo', 'Your photo editing tools', 'Pour éditer et retoucher tes images', 2, '["photoshop","lightroom","capture-one","affinity-photo","snapseed"]'),
('sofia-4', 'SOFIA', 4, 'Tes outils vidéo et motion', 'Your video & motion tools', 'Pour monter et animer', 2, '["premiere-pro","after-effects","davinci-resolve","final-cut-pro","capcut"]'),
('sofia-5', 'SOFIA', 5, 'Tes outils d''IA créative', 'Your creative AI tools', 'L''IA au service de ta créativité', 2, '["midjourney","stable-diffusion","firefly","leonardo-ai","runway","pika-labs","krea-ai","ideogram"]'),
('sofia-6', 'SOFIA', 6, 'Tes outils d''IA audio/voix', 'Your audio AI tools', 'Génération et édition audio par IA', 2, '["elevenlabs","suno","udio","adobe-podcast-ai","descript"]'),
('sofia-7', 'SOFIA', 7, 'Tes LLMs', 'Your LLMs', 'Les IA conversationnelles', 2, '["chatgpt","claude","gemini","perplexity"]'),
('sofia-8', 'SOFIA', 8, 'Tes outils de prototypage web', 'Your web prototyping tools', 'Pour créer des sites et prototypes', 2, '["webflow","framer","squarespace","wix","wordpress-com"]'),
('sofia-9', 'SOFIA', 9, 'Tes outils de gestion de projet', 'Your project management tools', 'Comment tu organises tes projets clients', 2, '["notion","trello","asana","monday-com","clickup"]'),
('sofia-10', 'SOFIA', 10, 'Tes outils de stockage et partage', 'Your storage & sharing tools', 'Où tu stockes et partages tes fichiers', 2, '["google-drive","dropbox","onedrive","wetransfer"]'),
('sofia-11', 'SOFIA', 11, 'Tes outils de communication', 'Your communication tools', 'Comment tu échanges avec tes clients', 2, '["slack","zoom","loom","calendly","cal-com"]'),
('sofia-12', 'SOFIA', 12, 'Tes outils de facturation', 'Your invoicing tools', 'Comment tu gères ta facturation', 2, '["stripe","paypal","wave","freshbooks"]'),
('sofia-13', 'SOFIA', 13, 'Tes outils de sécurité', 'Your security tools', 'Tes mots de passe et sécurité', 2, '["1password","bitwarden","dashlane","lastpass"]'),

-- ══════════════ MARC (Conseil) — 10 clusters ══════════════
('marc-1', 'MARC', 1, 'Tes outils CRM et prospection', 'Your CRM & prospecting tools', 'Comment tu gères tes prospects et clients', 2, '["hubspot","pipedrive","apollo-io","close","folk","capsule"]'),
('marc-2', 'MARC', 2, 'Tes LLMs', 'Your LLMs', 'Les IA que tu utilises au quotidien', 2, '["chatgpt","claude","gemini","perplexity","deepseek"]'),
('marc-3', 'MARC', 3, 'Tes outils de gestion de projet', 'Your project management tools', 'Comment tu structures tes missions', 2, '["notion","asana","monday-com","clickup","trello","basecamp"]'),
('marc-4', 'MARC', 4, 'Tes outils de présentation', 'Your presentation tools', 'Comment tu présentes tes livrables', 2, '["google-slides","canva","pitch","gamma","miro"]'),
('marc-5', 'MARC', 5, 'Tes outils de communication', 'Your communication tools', 'Comment tu communiques avec tes clients', 2, '["slack","zoom","teams","loom","calendly","cal-com"]'),
('marc-6', 'MARC', 6, 'Tes outils de comptabilité et facturation', 'Your accounting & invoicing tools', 'Ta gestion financière', 2, '["pennylane","tiime","indy","stripe","paypal","freshbooks"]'),
('marc-7', 'MARC', 7, 'Tes outils d''emailing', 'Your email tools', 'Comment tu gères tes emails et newsletter', 2, '["mailchimp","brevo","convertkit","substack"]'),
('marc-8', 'MARC', 8, 'Tes outils de stockage', 'Your storage tools', 'Où tu stockes tes documents', 2, '["google-drive","dropbox","onedrive","notion"]'),
('marc-9', 'MARC', 9, 'Tes outils d''automatisation', 'Your automation tools', 'Les workflows automatisés', 2, '["zapier","make","n8n"]'),
('marc-10', 'MARC', 10, 'Tes outils de sécurité', 'Your security tools', 'Tes mots de passe', 2, '["1password","bitwarden","dashlane","lastpass"]'),

-- ══════════════ ALIX (Content/Créateur) — 12 clusters ══════════════
('alix-1', 'ALIX', 1, 'Tes LLMs pour l''écriture', 'Your writing LLMs', 'Les IA qui t''aident à écrire', 2, '["chatgpt","claude","gemini","perplexity","jasper"]'),
('alix-2', 'ALIX', 2, 'Tes outils de newsletter', 'Your newsletter tools', 'Comment tu envoies ta newsletter', 2, '["substack","convertkit","mailchimp","brevo","beehiiv","ghost"]'),
('alix-3', 'ALIX', 3, 'Tes outils de réseaux sociaux', 'Your social media tools', 'Comment tu publies et planifies', 2, '["buffer","hootsuite","later","metricool","publer","socialbee"]'),
('alix-4', 'ALIX', 4, 'Tes outils de création visuelle', 'Your visual creation tools', 'Pour tes visuels et thumbnails', 2, '["canva","figma","photoshop","capcut","descript"]'),
('alix-5', 'ALIX', 5, 'Tes outils d''IA image/vidéo', 'Your image/video AI tools', 'L''IA pour créer du contenu visuel', 2, '["midjourney","stable-diffusion","runway","pika-labs","heygen","leonardo-ai"]'),
('alix-6', 'ALIX', 6, 'Tes outils de podcast/audio', 'Your podcast/audio tools', 'Pour enregistrer et éditer', 2, '["descript","riverside","otter-ai","adobe-podcast-ai","elevenlabs"]'),
('alix-7', 'ALIX', 7, 'Tes outils SEO et analytics', 'Your SEO & analytics tools', 'Comment tu suis tes performances', 2, '["plausible","posthog","hotjar","google-analytics","semrush"]'),
('alix-8', 'ALIX', 8, 'Tes outils de site web', 'Your website tools', 'Ton site ou blog', 2, '["wordpress-com","ghost","webflow","squarespace","wix","framer"]'),
('alix-9', 'ALIX', 9, 'Tes outils de gestion', 'Your management tools', 'Comment tu organises ton contenu', 2, '["notion","trello","asana","clickup","airtable"]'),
('alix-10', 'ALIX', 10, 'Tes outils de communication', 'Your communication tools', 'Comment tu échanges', 2, '["slack","discord","zoom","loom","calendly"]'),
('alix-11', 'ALIX', 11, 'Tes outils de monétisation', 'Your monetization tools', 'Comment tu monétises', 2, '["stripe","gumroad","lemonsqueezy","paypal"]'),
('alix-12', 'ALIX', 12, 'Tes outils de sécurité', 'Your security tools', 'Tes mots de passe', 2, '["1password","bitwarden","dashlane","lastpass"]'),

-- ══════════════ CLAIRE (Ops/Business) — 9 clusters ══════════════
('claire-1', 'CLAIRE', 1, 'Tes outils de comptabilité', 'Your accounting tools', 'Ta gestion financière quotidienne', 2, '["pennylane","tiime","indy","quickbooks","xero","freshbooks"]'),
('claire-2', 'CLAIRE', 2, 'Tes outils de gestion de projet', 'Your project management tools', 'Comment tu coordonnes les projets', 2, '["notion","asana","monday-com","clickup","trello","basecamp","jira"]'),
('claire-3', 'CLAIRE', 3, 'Tes outils CRM', 'Your CRM tools', 'Ta relation client', 2, '["hubspot","pipedrive","folk","salesforce","close"]'),
('claire-4', 'CLAIRE', 4, 'Tes outils de communication d''équipe', 'Your team communication tools', 'Les outils de collaboration', 2, '["slack","teams","zoom","loom","calendly","cal-com"]'),
('claire-5', 'CLAIRE', 5, 'Tes outils d''automatisation', 'Your automation tools', 'Tes workflows automatisés', 2, '["zapier","make","n8n"]'),
('claire-6', 'CLAIRE', 6, 'Tes LLMs', 'Your LLMs', 'L''IA au quotidien', 2, '["chatgpt","claude","gemini","perplexity"]'),
('claire-7', 'CLAIRE', 7, 'Tes outils RH et recrutement', 'Your HR & recruiting tools', 'Gestion des talents', 2, '["bamboohr","gusto","rippling","deel"]'),
('claire-8', 'CLAIRE', 8, 'Tes outils de stockage et docs', 'Your storage & docs tools', 'Où tu gères les documents', 2, '["google-drive","dropbox","onedrive","notion"]'),
('claire-9', 'CLAIRE', 9, 'Tes outils de sécurité', 'Your security tools', 'Sécurité et mots de passe', 2, '["1password","bitwarden","dashlane","lastpass","nordpass"]');

-- SEED DOUBLON RULES (common duplicates)
INSERT INTO doublon_rules (ids, message, savings, category) VALUES
('["chatgpt","claude"]', 'ChatGPT + Claude : tu paies 2 LLMs — un seul suffit pour la plupart des usages', 20, 'ai-general'),
('["chatgpt","gemini"]', 'ChatGPT + Gemini : doublon de LLM conversationnel', 20, 'ai-general'),
('["claude","gemini"]', 'Claude + Gemini : deux LLMs conversationnels en double', 20, 'ai-general'),
('["github-copilot","cursor"]', 'Copilot + Cursor : deux assistants de code IA — choisis ton favori', 10, 'ai-general'),
('["github-copilot","tabnine"]', 'Copilot + Tabnine : doublon d''autocomplétion IA', 10, 'ai-general'),
('["figma","sketch"]', 'Figma + Sketch : deux outils de design UI qui se chevauchent', 15, 'design-tools'),
('["figma","adobe-xd"]', 'Figma + Adobe XD : doublon d''outil de design d''interfaces', 12, 'design-tools'),
('["photoshop","affinity-photo"]', 'Photoshop + Affinity Photo : doublon de retouche photo', 12, 'design-tools'),
('["premiere-pro","davinci-resolve"]', 'Premiere Pro + DaVinci Resolve : deux logiciels de montage vidéo', 23, 'creation'),
('["premiere-pro","final-cut-pro"]', 'Premiere Pro + Final Cut Pro : doublon de montage vidéo', 23, 'creation'),
('["zapier","make"]', 'Zapier + Make : deux plateformes d''automatisation — une seule suffit', 19, 'automation'),
('["mailchimp","brevo"]', 'Mailchimp + Brevo : doublon d''emailing', 15, 'communication'),
('["mailchimp","convertkit"]', 'Mailchimp + ConvertKit : deux outils de newsletter', 15, 'communication'),
('["substack","convertkit"]', 'Substack + ConvertKit : chevauchement sur la newsletter', 10, 'communication'),
('["calendly","cal-com"]', 'Calendly + Cal.com : deux outils de prise de rendez-vous', 10, 'communication'),
('["slack","teams"]', 'Slack + Teams : deux messageries d''équipe', 8, 'communication-team'),
('["notion","clickup"]', 'Notion + ClickUp : chevauchement de gestion de projet', 10, 'project-management'),
('["asana","monday-com"]', 'Asana + Monday : deux outils de gestion de projet', 12, 'project-management'),
('["asana","trello"]', 'Asana + Trello : chevauchement de gestion de tâches', 10, 'project-management'),
('["trello","monday-com"]', 'Trello + Monday : doublon de gestion de projet', 10, 'project-management'),
('["google-drive","dropbox"]', 'Google Drive + Dropbox : deux stockages cloud', 10, 'storage'),
('["google-drive","onedrive"]', 'Google Drive + OneDrive : doublon de stockage', 7, 'storage'),
('["dropbox","onedrive"]', 'Dropbox + OneDrive : deux services de stockage en double', 10, 'storage'),
('["1password","dashlane"]', '1Password + Dashlane : deux gestionnaires de mots de passe', 5, 'security'),
('["1password","lastpass"]', '1Password + LastPass : doublon de gestionnaire de mots de passe', 5, 'security'),
('["bitwarden","dashlane"]', 'Bitwarden + Dashlane : doublon — Bitwarden est gratuit', 5, 'security'),
('["hubspot","pipedrive"]', 'HubSpot + Pipedrive : deux CRM — consolide sur un seul', 15, 'communication'),
('["midjourney","stable-diffusion"]', 'Midjourney + Stable Diffusion : deux générateurs d''images IA', 10, 'ai-general'),
('["midjourney","leonardo-ai"]', 'Midjourney + Leonardo AI : doublon de génération d''images', 10, 'ai-general'),
('["runway","pika-labs"]', 'Runway + Pika : deux outils de vidéo IA', 12, 'ai-general'),
('["webflow","framer"]', 'Webflow + Framer : deux constructeurs de sites', 15, 'nocode-web'),
('["webflow","squarespace"]', 'Webflow + Squarespace : doublon de création de site', 15, 'nocode-web'),
('["wix","squarespace"]', 'Wix + Squarespace : deux builders de sites en double', 12, 'nocode-web'),
('["pennylane","tiime"]', 'Pennylane + Tiime : deux outils de comptabilité freelance', 15, 'finance'),
('["pennylane","indy"]', 'Pennylane + Indy : doublon de comptabilité', 10, 'finance'),
('["buffer","hootsuite"]', 'Buffer + Hootsuite : deux outils de scheduling social', 10, 'communication'),
('["photoshop","adobe-creative-cloud"]', 'Photoshop seul + Adobe CC : Photoshop est inclus dans CC', 26, 'design-tools'),
('["illustrator","adobe-creative-cloud"]', 'Illustrator seul + Adobe CC : Illustrator est inclus dans CC', 26, 'design-tools'),
('["lightroom","adobe-creative-cloud"]', 'Lightroom seul + Adobe CC : Lightroom est inclus dans CC', 12, 'design-tools'),
('["premiere-pro","adobe-creative-cloud"]', 'Premiere Pro seul + Adobe CC : Premiere est inclus dans CC', 26, 'design-tools'),
('["after-effects","adobe-creative-cloud"]', 'After Effects seul + Adobe CC : AE est inclus dans CC', 26, 'design-tools');

-- SEED DISCOVERY QUESTIONS
INSERT INTO discovery_questions (id, persona, question, subtitle, options, condition_tool_ids, condition_type) VALUES
('dq-llm-usage', 'ALL', 'Comment utilises-tu tes LLMs au quotidien ?', 'Ça nous aide à savoir si tu as vraiment besoin de plusieurs abonnements', '[{"label":"Surtout du chat et des questions","impact":"review"},{"label":"Génération de contenu (articles, emails)","impact":"keep"},{"label":"Code et technique","impact":"keep"},{"label":"Je teste mais j''utilise peu","impact":"cancel"}]', '["chatgpt","claude","gemini","perplexity","deepseek"]', 'any'),
('dq-design-collab', 'SOFIA', 'Tu collabores avec des clients ou une équipe dans Figma ?', 'Le plan gratuit peut suffire pour le travail solo', '[{"label":"Oui, collaboration quotidienne","impact":"keep"},{"label":"Parfois, avec quelques clients","impact":"review"},{"label":"Non, je travaille seul(e)","impact":"review"}]', '["figma"]', 'any'),
('dq-adobe-usage', 'SOFIA', 'Tu utilises combien d''apps Adobe régulièrement ?', 'Si 3+ apps, le pack complet est plus rentable', '[{"label":"1-2 apps seulement","impact":"review"},{"label":"3-4 apps","impact":"keep"},{"label":"5+ apps","impact":"keep"}]', '["photoshop","illustrator","premiere-pro","after-effects","lightroom","indesign","adobe-creative-cloud"]', 'any'),
('dq-automation-volume', 'ALL', 'Combien de workflows automatisés as-tu actifs ?', 'Le nombre de scénarios détermine si le plan payant vaut le coup', '[{"label":"Moins de 5","impact":"review"},{"label":"5 à 20","impact":"keep"},{"label":"Plus de 20","impact":"keep"},{"label":"Je ne sais pas","impact":"review"}]', '["zapier","make","n8n"]', 'any'),
('dq-hosting-traffic', 'THEO', 'Quel volume de trafic sur tes apps déployées ?', 'Le bon plan dépend de ton trafic réel', '[{"label":"Side project, peu de trafic","impact":"review"},{"label":"Quelques milliers d''utilisateurs","impact":"keep"},{"label":"Production sérieuse, gros trafic","impact":"keep"}]', '["vercel","netlify","railway","render","heroku","fly-io"]', 'any'),
('dq-crm-contacts', 'MARC', 'Combien de contacts actifs dans ton CRM ?', 'En dessous de 500 contacts, le plan gratuit suffit souvent', '[{"label":"Moins de 100","impact":"review"},{"label":"100 à 1000","impact":"keep"},{"label":"Plus de 1000","impact":"keep"}]', '["hubspot","pipedrive","folk","close"]', 'any'),
('dq-newsletter-subs', 'ALIX', 'Combien d''abonnés à ta newsletter ?', 'Le prix monte vite avec le nombre d''abonnés', '[{"label":"Moins de 500","impact":"review"},{"label":"500 à 5000","impact":"keep"},{"label":"Plus de 5000","impact":"keep"}]', '["substack","convertkit","mailchimp","brevo","beehiiv"]', 'any'),
('dq-storage-usage', 'ALL', 'Tu utilises combien de Go de stockage cloud ?', 'Beaucoup paient pour du stockage qu''ils n''utilisent pas', '[{"label":"Moins de 15 Go (gratuit suffit)","impact":"review"},{"label":"15 à 100 Go","impact":"keep"},{"label":"Plus de 100 Go","impact":"keep"},{"label":"Aucune idée","impact":"review"}]', '["google-drive","dropbox","onedrive"]', 'any');
