
-- Insert Qonto tool
INSERT INTO tools (
  id, slug, name, category, short_description, short_description_en,
  long_description, long_description_en,
  default_monthly_price, pricing, pricing_en,
  affiliate_link, website_url, logo,
  tool_type, substitutable, bundle_parent, host_app,
  covers, functional_needs, verticals, personas,
  verdict, verdict_en, pros, pros_en, cons, cons_en, use_cases, use_cases_en,
  prescription_quality, prescription_block_reasons, prescription_context_questions,
  substitution_cluster_v2, decision_policy_v3, pricing_v5, force_silence,
  solo_relevance, team_relevance, time_gained_hours_per_month, free_alternative,
  alternatives, relevant_for, articles, seo
) VALUES (
  'qonto',
  'qonto',
  'Qonto',
  'finance',
  'Compte pro en ligne pour freelances et PME : IBAN FR, cartes, factures, compta synchronisée.',
  'Online business banking for freelancers and SMBs: French IBAN, cards, invoicing, accounting sync.',
  'Qonto, c''est le compte pro pensé pour les freelances et petites équipes. IBAN français, cartes Mastercard physiques et virtuelles, paiement et encaissement instantanés, facturation intégrée et synchro auto avec ton expert-comptable (Pennylane, Tiime, Indy, Cegid, etc.). À partir de 9€/mois HT (plan Basic solo). Alternative crédible à BNP/Société Générale pour qui veut un onboarding 100% en ligne en 10 minutes, des virements SEPA inclus, et un export comptable propre.',
  'Qonto is the business account built for freelancers and small teams. French IBAN, physical and virtual Mastercard cards, instant payments, built-in invoicing, and auto-sync with French accounting tools (Pennylane, Tiime, Indy, Cegid). From €9/month (Basic Solo plan). A real alternative to legacy banks: 100% online onboarding in 10 minutes, included SEPA transfers, clean accounting export.',
  9,
  '{"free": "Essai 30 jours", "paid": "Solo Basic 9€/mois HT — Solo Smart 19€/mois — Solo Premium 39€/mois — Team à partir de 29€/mois"}'::jsonb,
  '{"free": "30-day free trial", "paid": "Solo Basic €9/mo — Solo Smart €19/mo — Solo Premium €39/mo — Team from €29/mo"}'::jsonb,
  'https://lb.affilae.com/r/?p=69a078113f38abd84385e0d9&af=2648&lp=https%3A%2F%2Fqonto.com%2Ffr%3Futm_source%3Dinfluence',
  'https://qonto.com/fr',
  '',
  'gestion',
  true,
  null,
  null,
  '["compte-pro", "facturation", "cartes-paiement", "virements-sepa", "synchro-compta", "notes-frais"]'::jsonb,
  '["compte-pro", "facturation", "synchro-compta", "notes-frais"]'::jsonb,
  '["finance-ops", "freelance-ops", "business-ops"]'::jsonb,
  '["theo", "sofia", "marc", "claire", "alix"]'::jsonb,
  '{"keepIf": ["Tu factures tes clients en France ou en Europe et veux un IBAN FR propre", "Tu veux une synchro automatique avec ton expert-comptable (Pennylane, Tiime, Indy)", "Tu veux séparer perso/pro sans payer 25€/mois à une banque traditionnelle", "Tu as besoin de cartes virtuelles pour SaaS et abonnements"], "avoidIf": ["Tu n''as pas encore de structure (auto-entrepreneur sans CA — un compte courant dédié suffit la première année)", "Tu fais beaucoup de cash ou de chèques (Qonto ne les accepte pas)", "Ton activité est principalement hors zone SEPA"], "threshold": "Rentable dès 1500€ de CA/mois : tu gagnes 2-3h/mois de saisie compta + tu évites les frais cachés des banques traditionnelles (15-25€/mois)."}'::jsonb,
  '{"keepIf": ["You invoice clients in France or Europe and need a clean French IBAN", "You want auto-sync with your accountant (Pennylane, Tiime, Indy)", "You want to separate personal/business without paying €25/month to a legacy bank", "You need virtual cards for SaaS and subscriptions"], "avoidIf": ["You don''t have a registered business yet", "You handle a lot of cash or paper checks (Qonto doesn''t accept them)", "Your business is mostly outside the SEPA zone"], "threshold": "Profitable from €1,500/mo revenue: you save 2-3h/month on bookkeeping and avoid €15-25/month in legacy bank fees."}'::jsonb,
  '["IBAN français FR76 — accepté partout en France pour prélèvements et virements", "Onboarding 100% en ligne en 10 minutes (KBIS suffit)", "Synchro native avec Pennylane, Tiime, Indy, Cegid, Sage", "Cartes virtuelles illimitées pour cloisonner les abonnements SaaS", "Facturation intégrée avec relances automatiques (plan Smart+)", "Support client français réactif (chat + téléphone)"]'::jsonb,
  '["French FR76 IBAN accepted everywhere in France", "100% online onboarding in 10 minutes (KBIS only)", "Native sync with Pennylane, Tiime, Indy, Cegid, Sage", "Unlimited virtual cards to isolate SaaS subscriptions", "Built-in invoicing with auto-reminders (Smart+ plan)", "Reactive French customer support (chat + phone)"]'::jsonb,
  '["Pas de dépôt d''espèces ni de chèques", "Pas d''autorisation de découvert (uniquement avance ponctuelle Pay Later)", "Plan Basic limité à 30 virements SEPA inclus/mois (0,40€ au-delà)", "Pas de prêt bancaire classique (mais financement via Qonto Credit)"]'::jsonb,
  '["No cash or check deposits", "No traditional overdraft (only Pay Later short-term advance)", "Basic plan capped at 30 SEPA transfers/month included (€0.40 beyond)", "No traditional bank loan (but Qonto Credit financing available)"]'::jsonb,
  '["Encaisser ses clients par virement SEPA avec un IBAN FR", "Émettre des factures conformes (mentions légales, TVA, numérotation auto)", "Synchroniser automatiquement les transactions avec son expert-comptable", "Gérer les notes de frais et justificatifs en photo depuis l''app", "Cloisonner les abonnements SaaS avec des cartes virtuelles dédiées", "Préparer la TVA avec un export propre par catégorie"]'::jsonb,
  '["Receive client payments via SEPA with a French IBAN", "Issue compliant invoices (legal mentions, VAT, auto-numbering)", "Auto-sync transactions with your accountant", "Manage expense reports with photo receipts from the app", "Isolate SaaS subscriptions with dedicated virtual cards", "Prep VAT with clean per-category exports"]'::jsonb,
  'oui',
  '[]'::jsonb,
  '["business_structure", "monthly_revenue", "needs_invoicing"]'::jsonb,
  'compte-pro',
  '{"auto_cancel_allowed": false, "auto_replace_allowed": false, "auto_downgrade_allowed": true, "requires_context_questions": false, "never_auto_cancel_reason": "Outil bancaire critique — ne jamais résilier automatiquement.", "default_decision_lane": "prescribe"}'::jsonb,
  '{"compare_price_monthly_eur": 9, "compare_plan_name": "Solo Basic", "compare_plan_kind": "seat", "price_reliability": "high", "usage_sensitive": false, "location_sensitive": true, "cautions": ["Prix HT — TVA 20% applicable. Frais additionnels au-delà de 30 virements SEPA/mois sur le plan Basic."], "source_domain": "qonto.com", "verified_on": "2026-05-05", "official_source_url": "https://qonto.com/fr/pricing", "verification_status": "official_verified"}'::jsonb,
  false,
  'high',
  'high',
  3,
  null,
  '["shine", "blank", "propulse-ca", "revolut-business"]'::jsonb,
  '["freelance", "consultant", "agence", "startup", "pme"]'::jsonb,
  '[]'::jsonb,
  '{"metaTitle": "Qonto avis 2026 : compte pro freelance, prix, alternatives | Tooltrim", "metaDescription": "Qonto pour freelances : 9€/mois, IBAN FR, synchro Pennylane/Tiime/Indy. Notre verdict honnête, les limites réelles, et quand préférer Shine ou Revolut Business."}'::jsonb
);

-- Add qonto to existing clusters
UPDATE clusters SET tool_ids = '["pennylane","tiime","indy","stripe","paypal","freshbooks","qonto"]'::jsonb WHERE id = 'marc-6';
UPDATE clusters SET tool_ids = '["dext","freshbooks","indy","pennylane","quickbooks","tiime","xero","qonto"]'::jsonb WHERE id = 'claire-1';
